from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model import Model
from api import util


class HelloWorldResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, version=None):  # noqa: E501
        """HelloWorldResponse - a model defined in OpenAPI

        :param message: The message of this HelloWorldResponse.  # noqa: E501
        :type message: str
        :param version: The version of this HelloWorldResponse.  # noqa: E501
        :type version: str
        """
        self.openapi_types = {
            'message': str,
            'version': str
        }

        self.attribute_map = {
            'message': 'message',
            'version': 'version'
        }

        self._message = message
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'HelloWorldResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HelloWorldResponse of this HelloWorldResponse.  # noqa: E501
        :rtype: HelloWorldResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this HelloWorldResponse.


        :return: The message of this HelloWorldResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this HelloWorldResponse.


        :param message: The message of this HelloWorldResponse.
        :type message: str
        """

        self._message = message

    @property
    def version(self) -> str:
        """Gets the version of this HelloWorldResponse.


        :return: The version of this HelloWorldResponse.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this HelloWorldResponse.


        :param version: The version of this HelloWorldResponse.
        :type version: str
        """

        self._version = version
